LetsEat/Controllers/LetsEatController.cs
using LetsEat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace LetsEat.Controllers
{
    [Authorize]
    public class LetsEatController : Controller
    {

        private readonly LetsEatContext _db; 

        public LetsEatController(LetsEatContext db)
        {
            _db = db;
        }

        public IActionResult ShowAllFavorites(string sortOrder)
        {
            ViewData["CategorySortParm"] = sortOrder == "Category" ? "Category_desc" : "Category";
            ViewData["RatingSortParm"] = sortOrder == "Rating" ? "Rating_desc" : "Rating";
            var user = FindUser();
            var recipes = from all in _db.FavoriteRecipes
                            join Recipe in _db.UserFavoriteRecipes on all.Id equals Recipe.RecipeId
                            where Recipe.UserId.Equals(user)
                            select all;

            List<FavoriteRecipes> RecipeList = recipes.ToList();
            // create list of viewmodel objects to populate
            List<FavoriteRecipeViewModel> OutputList = new List<FavoriteRecipeViewModel>();
            foreach (var item in RecipeList)
            {
                FavoriteRecipeViewModel vm = new FavoriteRecipeViewModel();
                // find user favorite rating and category
                UserFavoriteRecipes ur = new UserFavoriteRecipes();

                ur = _db.UserFavoriteRecipes.Find(FindUser(), item.Id);
                if (!string.IsNullOrWhiteSpace(ur.Category))
                {
                    vm.Category = ur.Category;
                }
                vm.Rating = ur.Rating;
                vm.Title = item.Title;
                vm.RecipeID = ur.RecipeId;
                vm.RecipeUrl = item.RecipeUrl;
                vm.Ingredients = item.Ingredients;
                vm.Thumbnail = item.Thumbnail;
                OutputList.Add(vm);
            }

            switch (sortOrder)
            {
                case "Category":
                    OutputList = OutputList.OrderBy(x => x.Category).ToList();
                    break;
                case "Category_desc":
                    OutputList = OutputList.OrderByDescending(x => x.Category).ToList();
                    break;
                case "Rating":
                    OutputList = OutputList.OrderBy(x => x.Rating).ToList();
                    break;
                case "Rating_desc":
                    OutputList = OutputList.OrderByDescending(x => x.Rating).ToList();
                    break;
                default:
                    break;
            }
            return View(OutputList);
        }
        public async Task<IActionResult> EditFavorite(int id)
        {
            FavoriteRecipeViewModel vm = new FavoriteRecipeViewModel();
            FavoriteRecipes fr = _db.FavoriteRecipes.Find(id);
            vm.Title = fr.Title;
            vm.Ingredients = fr.Ingredients;
            vm.Thumbnail = fr.Thumbnail;
            vm.RecipeUrl = fr.RecipeUrl;
            // find user favorite rating and category
            var ur = _db.UserFavoriteRecipes.Find(FindUser(), fr.Id);
            vm.Category = ur.Category;
            vm.Rating = ur.Rating;
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> EditFavorite(FavoriteRecipes fr, string Category, byte Rating)
        {
            // create primary key from values
            string currentUserID = FindUser();
            int currentRecipeID = fr.Id;
            var ur = _db.UserFavoriteRecipes.Find(currentUserID, currentRecipeID);
            // adding values to selected record
            ur.Category = Category;
            ur.Rating = Rating;
            // necessary due to values being stored in main recipe table visible to all users
            fr.Category = "";
            fr.Rating = null;

            _db.UserFavoriteRecipes.Update(ur);
            _db.FavoriteRecipes.Update(fr);
            await _db.SaveChangesAsync();

            return RedirectToAction("ShowAllFavorites");
        }
        [HttpGet]
        public async Task<IActionResult> GetRecipe(Result r)
        {
            TempData["Name"] = r.title;

            return View(r);
        }
        [HttpPost]
        public async Task<IActionResult> AddToFavorites(string title, string recipeUrl, string ingredients, string thumbnail)
        {
            FavoriteRecipes r = new FavoriteRecipes();
            r.Title = title;
            r.RecipeUrl = recipeUrl;
            r.Ingredients = ingredients;
            r.Thumbnail = thumbnail;

            // retrieve current ID for favorite recipe if it exists
            int favoriteID = (from RecipeURL in _db.FavoriteRecipes
                             where RecipeURL.RecipeUrl.Equals(recipeUrl)
                             select RecipeURL.Id).FirstOrDefault();

            // retrieve current ID for favorite recipe if it exists
            int existsInUserFavorites = 0;
            existsInUserFavorites = (from Recipe in _db.UserFavoriteRecipes
                             where Recipe.RecipeId.Equals(favoriteID)
                             select Recipe.RecipeId).FirstOrDefault();

            // adds currently selected recipe to FavoriteRecipes and newly added RecipeID and UserID to UserFavoriteRecipes
            if (ModelState.IsValid && favoriteID == 0 && existsInUserFavorites == 0)

            {
                await _db.FavoriteRecipes.AddAsync(r);
                await _db.SaveChangesAsync();

                var user = FindUser();
                UserFavoriteRecipes f = new UserFavoriteRecipes(user, r.Id);

                await _db.UserFavoriteRecipes.AddAsync(f);
                await _db.SaveChangesAsync();

                return RedirectToAction("ShowAllFavorites");
            }

            // if the currently selected recipe exists in database it will only add that recipeID and current UserID to UserFavoriteRecipes table
            if (favoriteID != 0 && existsInUserFavorites == 0)
            {
                var user = FindUser();
                UserFavoriteRecipes f = new UserFavoriteRecipes(user, favoriteID);

                await _db.UserFavoriteRecipes.AddAsync(f);
                await _db.SaveChangesAsync();

                return RedirectToAction("ShowAllFavorites");
            }
            return RedirectToAction("ShowAllFavorites");
        }

        [HttpGet]
        public IActionResult UpdateFavorite(int Id)
        {
            FavoriteRecipes r = _db.FavoriteRecipes.Find(Id);
            return View(r);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateFavorite(FavoriteRecipes r)
        {
            if (ModelState.IsValid)
            {
                _db.FavoriteRecipes.Update(r);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction("ShowAllFavorites");
        }
        [HttpGet]
        public IActionResult DeleteFavorite(int Id)
        {
            string user = FindUser();
            FavoriteRecipes r = _db.FavoriteRecipes.Find(Id);
            // create primary key from values
            int currentRecipeID = r.Id;
            var ur = _db.UserFavoriteRecipes.Find(user, currentRecipeID);
            FavoriteRecipeViewModel vm = new FavoriteRecipeViewModel();

            vm.Title = r.Title;
            vm.Ingredients = r.Ingredients;
            vm.RecipeUrl = r.RecipeUrl;
            vm.Category = ur.Category;
            vm.Rating = ur.Rating;
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteFavorite(FavoriteRecipes r)
        {
            var recipe = _db.UserFavoriteRecipes.Where(x => x.RecipeId == r.Id).First();
            _db.UserFavoriteRecipes.Remove(recipe);

            string recipeID = r.Id.ToString();
            int recipeIDint = int.Parse(recipeID);
            //setup to check other users with this recipe as favorite before deleting
            var count = _db.UserFavoriteRecipes.Where(x => x.RecipeId == r.Id);
            if(count.Count() == 1)
            {
                var recipeObject = _db.FavoriteRecipes.Where(x => x.Id == r.Id).First();
                _db.FavoriteRecipes.Remove(recipeObject);
            }            
            
            await _db.SaveChangesAsync();

            return RedirectToAction("ShowAllFavorites");
        }
        public IActionResult RandomFavorite()
        {
            var user = FindUser();
            var recipes = from r in _db.FavoriteRecipes
                          where _db.UserFavoriteRecipes.Any(x => x.UserId == user && x.RecipeId == r.Id)
                          select r;
            var randomRecipe = recipes.OrderBy(x => Guid.NewGuid()).FirstOrDefault();
            
            if (randomRecipe != null)
            {     
                // create primary key from values
                int currentRecipeID = randomRecipe.Id;
                var ur = _db.UserFavoriteRecipes.Find(user, currentRecipeID);
                FavoriteRecipeViewModel vm = new FavoriteRecipeViewModel();
    
                vm.Title = randomRecipe.Title;
                vm.Ingredients = randomRecipe.Ingredients;
                vm.RecipeUrl = randomRecipe.RecipeUrl;
                vm.Category = ur.Category;
                vm.Rating = ur.Rating;
                return View(vm);
            } 
            return View("ShowAllFavorites");
        }
        public string FindUser()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            return userId;
        }
    }
}

LetsEat/Views/LetsEat/DeleteFavorite.cshtml
@model FavoriteRecipeViewModel
<h2>Remove from Favorites</h2>

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text"><u>Ingredients Needed:</u> @Model.Ingredients</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Rating: @Model.Rating/5</li>
        <li class="list-group-item">Category: @Model.Category</li>
    </ul>
    <div class="card-body">
        <a href="@Model.RecipeUrl" target="_blank" class="card-link">Recipe Details</a>
    </div>
</div>
<br />
<p><b>Are you sure you want to remove this recipe from your favorites?</b></p>
<form asp-controller="LetsEat" asp-action="DeleteFavorite" method="post">
    <input type="hidden" name="Title" value="@Model.Title" />
    <input type="hidden" name="RecipeUrl" value="@Model.RecipeUrl" />
    <input type="hidden" name="Ingredients" value="@Model.Ingredients" />
    <input type="hidden" name="Thumbnail" value="@Model.Thumbnail" />
    <input type="hidden" name="Rating" value="@Model.Rating" />
    <input type="hidden" name="Category" value="@Model.Category" />
    <input class="btn-light" type="submit" value="Yes" />
    <input class="btn-light" type="submit" value="No" asp-controller="LetsEat" asp-action="ShowAllFavorites" />
</form>

LetsEat/Views/LetsEat/EditFavorite.cshtml
@model LetsEat.Models.FavoriteRecipeViewModel

@{
    ViewData["Title"] = "Edit Favorite";
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "1",
        Value = "1"
    });
    listItems.Add(new SelectListItem
    {
        Text = "2",
        Value = "2"
    });
    listItems.Add(new SelectListItem
    {
        Text = "3",
        Value = "3"
    });
    listItems.Add(new SelectListItem
    {
        Text = "4",
        Value = "4"
    });
    listItems.Add(new SelectListItem
    {
        Text = "5",
        Value = "5"
    });
}
<h1>Edit Favorite Recipe</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditFavorite" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RecipeID" />
            <input type="hidden" asp-for="RecipeUrl" />
            <input type="hidden" asp-for="Thumbnail" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredients" class="control-label"></label>
                <input asp-for="Ingredients" class="form-control" />
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p class="control-label">Rating</p>
                @Html.DropDownListFor(model => Model.Rating, listItems, "-- Choose Rating --")
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="LetsEat" asp-action="ShowAllFavorites">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LetsEat/Views/LetsEat/GetRecipe.cshtml
@model Result

<h3>Confirm you want to add @TempData["Name"] to favorites</h3>

<form asp-controller="FavoriteRecipes" asp-action="AddToFavorites" method="post">
    <input type="hidden" name="Id" />
    <input type="hidden" name="RecipeUrl" value="@Model.href" />
    <input type="hidden" name="Title" value="@Model.title" />
    <input type="hidden" name="Ingredients" value="@Model.ingredients" />
    <input type="hidden" name="Thumbnail" value="@Model.thumbnail" />
    <input type="number" name="Rating" min="0" max="10" />
    <input type="text" name="Category" />
    <input type="submit" value="Add to Favorites" />
</form>

LetsEat/Views/LetsEat/RandomFavorite.cshtml
@model FavoriteRecipeViewModel

<h3>How about. . .</h3>
<div class="card align-content-center" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text"><u>Ingredients Needed:</u> @Model.Ingredients</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            @{
                string rating = "";
                string category = "";
            }
            Rating:
            @if (Model.Rating != 0)
            {
                rating = @Model.Rating.ToString() + "/5";
            }
            else
            {
                rating = "N/A";
            }
            @rating
        </li>
        <li class="list-group-item">
            Category:
            @if (!(Model.Category is null))
            {
                category = @Model.Category;
            }
            else
            {
                category = "N/A";
            }
            @category
        </li>
    </ul>
    <div class="card-body">
        <a href="@Model.RecipeUrl" target="_blank" class="card-link">Recipe Details</a>
    </div>
</div>
<br />
<button class="btn btn-light" type="submit" onclick="window.location.reload()">Not in the mood</button>

LetsEat/Views/LetsEat/ShowAllFavorites.cshtml
@model List<FavoriteRecipeViewModel>

<div>
    <h1 class="body">Your Favorite Recipes</h1>
</div>
@if (Model != null)
{
    <table class="table table-bordered table-striped table-dark table-hover">
        <tr>
            <th class="text-center">Image / Link</th>
            <th class="text-center">Name</th>
            <th class="text-center">Ingredients</th>
            <th class="text-center"><a asp-action="ShowAllFavorites" asp-route-searchString="@ViewData["CurrentFilter"]" asp-route-sortOrder="@ViewData["CategorySortParm"]">@Html.DisplayNameFor(model => model[0].Category)</a></th>
            <th class="text-center"><a asp-action="ShowAllFavorites" asp-route-searchString="@ViewData["CurrentFilter"]" asp-route-sortOrder="@ViewData["RatingSortParm"]">@Html.DisplayNameFor(model => model[0].Rating)</a></th>
            <th class="text-center">Edit</th>
            <th class="text-center">Remove</th>
        </tr>
        @foreach (FavoriteRecipeViewModel r in Model)
        {
            <tr>
                @if (!string.IsNullOrEmpty(r.Thumbnail))
                {
                    <td><a href="@r.RecipeUrl" target="_blank"><img src="@r.Thumbnail" /></a></td>
                }
                else
                {
                    <td><a href="@r.RecipeUrl" target="_blank"><img src="../img/null_img.png" height="110" width="110" /></a></td>
                }
                <td style="text-align:center">@r.Title</td>
                <td style="text-transform: capitalize">@r.Ingredients</td>
                <td style="text-align:center">
                    @if (!(r.Category is null))
                    {
                        string value = r.Category;
                        @value;
                    }
                    else
                    {
                        string output = "N/A";
                        @output;
                    }
                </td>
                <td style="text-align:center">
                    @if (r.Rating > 0)
                    {
                        string value = r.Rating.ToString();
                        @value;
                    }
                    else
                    {
                        string output = "N/A";
                        @output;
                    }
                </td>
                <td>
                    <a asp-controller="LetsEat" asp-action="EditFavorite" asp-route-id="@r.RecipeID" class="btn btn-success align">Edit Entry</a>
                </td>
                <td>
                    <a asp-controller="LetsEat" asp-action="DeleteFavorite" asp-route-id="@r.RecipeID" class="btn btn-danger align">Remove Favorite</a>
                </td>
            </tr>
        }
        }
    </table>
}
else
{
    <p>Looks like you don't have any favorites. Find some using our <a asp-controller="Home" asp-action="Index"><b>search tool</b></a>!</p>
}

LetsEat/Views/LetsEat/UpdateFavorite.cshtml
@model FavoriteRecipes

<h1>Update @Model.Title</h1>

<form asp-controller="LetsEat" asp-action="UpdateFavorite" method="post">
    <input type="hidden" name="Title" value="@Model.Title" />
    <input type="hidden" name="RecipeUrl" value="@Model.RecipeUrl" />
    <input type="hidden" name="Ingredients" value="@Model.Ingredients" />
    <input type="hidden" name="Thumbnail" value="@Model.Thumbnail" />
    <input type="number" name="Rating" value="@Model.Rating" />
    <input type="text" name="Category" value="@Model.Category" />
    <input type="submit" value="Save Changes" />
    <input type="submit" value="Cancel" asp-controller="LetsEat" asp-action="ShowAllFavorites" />
</form>